config/routes.rb
Rails.application.routes.draw do
 

  devise_for :users

   root 'vehicles#index'

    resources :locations
    resources :vehicles 
    resources :vehicle_records
    resources :vehicle_payments
    resources :accessories
    resources :drivers
    resources :clients
    resources :routes

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
    if user.role? "super_admin"
      can :manage, :all
    elsif user.role? "admin"
      can :read, :all
    else
      can :read, :all
    end
    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/accessory.rb
class Accessory < ActiveRecord::Base
	belongs_to :vehicle
	validates_presence_of :name,:cost,:model,:serial_no,:invoice_image
	
	validates_numericality_of :serial_no
	
	has_attached_file :invoice_image
  	#do_not_validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	do_not_validate_attachment_file_type :invoice_image

end

app/models/client.rb
class Client < ActiveRecord::Base

  has_many :vehicles, through: :vehicle_drivers

  validates_presence_of :name, :p_o_c, :email, :phone, :location

  validates_numericality_of :phone
  validates_uniqueness_of :email ,:phone
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  validates_length_of :phone, is: 10

end

app/models/driver.rb
class Driver < ActiveRecord::Base

	has_attached_file :image_p
	has_attached_file :image_dl
    
    validates_attachment_content_type :image_p, :image_dl, content_type: /\Aimage\/.*\Z/
	
	has_many :vehicle_drivers
	has_many :vehicles, through: :vehicle_drivers

	validates_presence_of :name, :age, :blood_group, :mobile_no, :address, :emergency_contact, :dl_expiration,:image_dl,:image_p, :driver_salary

	validates_numericality_of :mobile_no, :emergency_contact
	validates_uniqueness_of :mobile_no

	validate :check_date,:check_duplication_of_mobile
	validates_length_of :mobile_no, :emergency_contact,is: 10

	private
	def check_date
		if self.dl_expiration < Date.today
			errors.add(:dl_expiration,"Expiration Date should be greater than today")
		end
	end
	def check_duplication_of_mobile
		if self.mobile_no == self.emergency_contact
			errors.add(:emergency_contact, " Number shouldnot be same as Mobile number")
		end
	end

end

app/models/location.rb
class Location < ActiveRecord::Base

	has_many :route_locations
	has_many :routes, through: :route_locations
	validates_presence_of :name, :latitude,:longitude

end

app/models/permission.rb
class Permission < ActiveRecord::Base
    
    validates_presence_of :role_id, :user_id
    belongs_to :user
	belongs_to :role
    
end

app/models/role.rb
class Role < ActiveRecord::Base
    
    has_many :permissions
	has_many :users, through: :permissions
    
end

app/models/route.rb
class Route < ActiveRecord::Base

	has_many :vehicles, through: :vehicle_routes
	has_many :route_locations
	has_many :locations, through: :route_locations
	validates_presence_of :name
end

app/models/route_location.rb
class RouteLocation < ActiveRecord::Base
	
	belongs_to :route
	belongs_to :location

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

        has_many :permissions
	      has_many :roles, through: :permissions

        def role? (role)
          self.roles.pluck(:name).include?(role)
        end

end

app/models/vehicle_client.rb
class VehicleClient < ActiveRecord::Base
	belongs_to :vehicle
	belongs_to :client
end

app/models/vehicle_driver.rb
class VehicleDriver < ActiveRecord::Base
	belongs_to :vehicle
	belongs_to :driver

end

app/models/vehicle_payment.rb
class VehiclePayment < ActiveRecord::Base
	belongs_to :vehicle
	validates_presence_of :amount_type,:amount_paid,:payment_date,:mode_of_payment
	validate :check_date 
	has_attached_file :image
  	#do_not_validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	do_not_validate_attachment_file_type :image
 	#before_save :month

private
	def check_date
		if self.payment_date > Date.today
			errors.add(:payment_date," should Not be greater than today")
		end
	end
		
end

app/models/vehicle_route.rb
class VehicleRoute < ActiveRecord::Base
	belongs_to :vehicle 
	belongs_to :route

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  def index
  	@clients = Client.all
  end

  
  def new
  	@client = Client.new
  end

  
  def create
  	@client = Client.new(client_params)
     Alert.add_client(@client,current_user).deliver!
  	if @client.save
  		redirect_to clients_path, notice: "Successfully created a new Client"
  	else
  		render action: "new"
  	end
  end

  
  def edit
  	@client = Client.find(params[:id])
  end

  
  def update
     @client = Client.find(params[:id])
     if @client.update_attributes(client_params)
     	redirect_to clients_path, notice: "Successfully update the client"
     else
     	render action: "edit"
     end
  end

  
  def destroy
  	@client = Client.find(params[:id])
  	@client.destroy
  	redirect_to clients_path, notice: "Successfully delete the client"
  end

  def show
  	@client = Client.find(params[:id])
  end

  private

  def client_params
      params[:client].permit(:name, :p_o_c, :email, :phone, :location )    
  end

end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController

	def index
        @routes = Route.all 
	end

	def new
		@route = Route.new
	end

	def create
		@route = Route.new(route_params)
		if @route.save
			redirect_to routes_path, notice: "Successfully Route created"
		else
			render action: "new"
		end
	end

	
	def edit
		@route = Route.find(params[:id])
	end

	def update
		@route = Route.find(params[:id])
		if @route.update_attributes(route_params)
			redirect_to routes_path, notice: "Successfully Route updated"
		else
			render action: "edit"
		end
	end

	def destroy
        @route = Route.find(params[:id])
        @route.destroy
        redirect_to routes_path, notice: "Successfully delete Route"
	end

	def show
		@route = Route.find(params[:id])
	end


	private
	def	route_params
        params[:route].permit(:id,:name,:location_ids => [])  
    end	

end

app/helpers/accessories_helper.rb
module AccessoriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/clients/edit.html.erb
<h3>Edit Client</h3>

<%= form_for @client do |f| %>

  <% if @client.errors.any? %>
   <ul>
   	   <% for msg in @client.errors.full_messages %>
   	   <li><%= msg %></li>
   	   <% end %>
   </ul>
   <% end %>

    <label>Name:</label><br/>
	<%= f.text_field :name %><br/>

    <label>Point of Contact:</label><br/>
	<%= f.text_field :p_o_c %><br/>

	<label>Email:</label><br/>
	<%= f.email_field :email %><br/>

	<label>Phone:</label><br/>
	<%= f.text_field :phone %><br/>

	<label>Location:</label><br/>
	<%= f.text_field :location %><br/>

	<input type="submit" class="btn btn-info" value="Create Client">
	
<% end %>

app/views/clients/index.html.erb
<h3>Listing Clients</h3>

<br/>
<div class="table-responsive">          
  <table class="table" border="1">
    <thead>
           <tr>
           	   <th> </th>
           	   <th>Name</th>
           	   <th>Point of Contact</th>
           	   <th>Email</th>
           	   <th>Phone</th>
           	   <th>Location</th>
           	   <th>Action</th>
           </tr>
      </thead>

      <tbody>
      	   <% @clients.each_with_index do |client,index| %>
                   <tr>
                        <td><%= index + 1 %></td>
                        <td><%= client.name %></td>
                        <td><%= client.p_o_c %></td>
                        <td><%= client.email %></td>
                        <td><%= client.phone %></td>
                        <td><%= client.location %></td>
                        <td><%= link_to "Show", client_path(client.id) %> |
          	    	        <%= link_to "Edit", edit_client_path(client.id) %> |
          	    	        <%= link_to "Delete", client_path(client.id), method: :delete, data: {confirm: "Are you sure?"} %></td>  
                   </tr>
      	   <% end %>
      </tbody>
</table>
</div>
<br/>


<%= link_to "Add Client", new_client_path %><br/><br/>

<%= link_to "Vehicle Details",vehicles_path %>

app/views/clients/new.html.erb
<h3>Add New Client</h3>

<%= form_for @client do |f| %>

 <% if @client.errors.any? %>
   <ul>
   	   <% for msg in @client.errors.full_messages %>
   	   <li><%= msg %></li>
   	   <% end %>
   </ul>
   <% end %>

    <label>Name:</label><br/>
	<%= f.text_field :name %><br/>

    <label>Point of Contact:</label><br/>
	<%= f.text_field :p_o_c %><br/>

	<label>Email:</label><br/>
	<%= f.email_field :email %><br/>

	<label>Phone:</label><br/>
	<%= f.text_field :phone %><br/>


	<label>Location:</label><br/>
	<%= f.text_field :location %><br/><br/>

	<input type="submit" class="btn btn-info" value="Create Client">
	
<% end %>

app/views/clients/show.html.erb
<%= javascript_tag do %>
  function goBack() {
    window.history.back();
}
<% end %>
<h3><%= @client.name %></h3>

<%= link_to "Edit",edit_client_path(@client.id) %> | <%= link_to "Delete", client_path(@client.id),method: :delete, data: {confirm: "Are you sure?"} %>
<hr/>
<%= link_to "Vehicle Details",vehicles_path %><br/>

Point of Contact : <%= @client.p_o_c %><br/>
Email : <%= @client.email %><br/>
Phone : <%= @client.phone %><br/>
Location : <%= @client.location %><br/> 

<a href="#" onclick="goBack()">Back</a>