config/routes.rb
Rails.application.routes.draw do
 

  devise_for :users

   root 'vehicles#index'

    resources :locations
    resources :vehicles 
    resources :vehicle_records
    resources :vehicle_payments
    resources :accessories
    resources :drivers
    resources :clients
    resources :routes

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
    if user.role? "super_admin"
      can :manage, :all
    elsif user.role? "admin"
      can :read, :all
    else
      can :read, :all
    end
    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/accessory.rb
class Accessory < ActiveRecord::Base
	belongs_to :vehicle
	validates_presence_of :name,:cost,:model,:serial_no,:invoice_image
	
	validates_numericality_of :serial_no
	
	has_attached_file :invoice_image
  	#do_not_validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	do_not_validate_attachment_file_type :invoice_image

end

app/models/client.rb
class Client < ActiveRecord::Base

  has_many :vehicles, through: :vehicle_drivers

  validates_presence_of :name, :p_o_c, :email, :phone, :location

  validates_numericality_of :phone
  validates_uniqueness_of :email ,:phone
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  validates_length_of :phone, is: 10

end

app/models/driver.rb
class Driver < ActiveRecord::Base

	has_attached_file :image_p
	has_attached_file :image_dl
    
    validates_attachment_content_type :image_p, :image_dl, content_type: /\Aimage\/.*\Z/
	
	has_many :vehicle_drivers
	has_many :vehicles, through: :vehicle_drivers

	validates_presence_of :name, :age, :blood_group, :mobile_no, :address, :emergency_contact, :dl_expiration,:image_dl,:image_p, :driver_salary

	validates_numericality_of :mobile_no, :emergency_contact
	validates_uniqueness_of :mobile_no

	validate :check_date,:check_duplication_of_mobile
	validates_length_of :mobile_no, :emergency_contact,is: 10

	private
	def check_date
		if self.dl_expiration < Date.today
			errors.add(:dl_expiration,"Expiration Date should be greater than today")
		end
	end
	def check_duplication_of_mobile
		if self.mobile_no == self.emergency_contact
			errors.add(:emergency_contact, " Number shouldnot be same as Mobile number")
		end
	end

end

app/models/location.rb
class Location < ActiveRecord::Base

	has_many :route_locations
	has_many :routes, through: :route_locations
	validates_presence_of :name, :latitude,:longitude

end

app/models/permission.rb
class Permission < ActiveRecord::Base
    
    validates_presence_of :role_id, :user_id
    belongs_to :user
	belongs_to :role
    
end

app/models/role.rb
class Role < ActiveRecord::Base
    
    has_many :permissions
	has_many :users, through: :permissions
    
end

app/models/route.rb
class Route < ActiveRecord::Base

	has_many :vehicles, through: :vehicle_routes
	has_many :route_locations
	has_many :locations, through: :route_locations
	validates_presence_of :name
end

app/models/route_location.rb
class RouteLocation < ActiveRecord::Base
	
	belongs_to :route
	belongs_to :location

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

        has_many :permissions
	      has_many :roles, through: :permissions

        def role? (role)
          self.roles.pluck(:name).include?(role)
        end

end

app/models/vehicle_client.rb
class VehicleClient < ActiveRecord::Base
	belongs_to :vehicle
	belongs_to :client
end

app/models/vehicle_driver.rb
class VehicleDriver < ActiveRecord::Base
	belongs_to :vehicle
	belongs_to :driver

end

app/models/vehicle_payment.rb
class VehiclePayment < ActiveRecord::Base
	belongs_to :vehicle
	validates_presence_of :amount_type,:amount_paid,:payment_date,:mode_of_payment
	validate :check_date 
	has_attached_file :image
  	#do_not_validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	do_not_validate_attachment_file_type :image
 	#before_save :month

private
	def check_date
		if self.payment_date > Date.today
			errors.add(:payment_date," should Not be greater than today")
		end
	end
		
end

app/models/vehicle_route.rb
class VehicleRoute < ActiveRecord::Base
	belongs_to :vehicle 
	belongs_to :route

end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController

before_filter :authenticate_user!

#load_and_authorize_resource

	def index
		@vehicles = Vehicle.all
		@drivers = Driver.all
		@clients = Client.all
		@locations = Location.all
		@routes = Route.all
	end

	def new
		@vehicle = Vehicle.new
	end
	def create
		@vehicle = Vehicle.new(vehicle_params)
		if @vehicle.save
			redirect_to vehicles_path,notice: "Successfully created the #{@vehicle.name} vehicle details"
		else
			render action: "new"
		end
	end
	
	def show
		@driver = Driver.new
		@drivers =Driver.all
		@vehicle = Vehicle.find(params[:id])
		@accessory = Accessory.new
		@accessories = Accessory.all
		@vehicle_payments = VehiclePayment.all
		@vehicle_payment_months = @vehicle_payments.group_by{|t| t.payment_date.beginning_of_month }
		@vehicle_payment = VehiclePayment.new
		@vehicle_payments =VehiclePayment.all

	end
	
	def edit
		@vehicle = Vehicle.find(params[:id] )

	end
	
	def update
		@vehicle = Vehicle.find(params[:id])
		if @vehicle.update_attributes(vehicle_params)
			redirect_to vehicles_path,notice: "Successfully updated the #{@vehicle.name}Vehicle details"
		else
			render action:"edit"
		end
	end

	def destroy
		@vehicle = Vehicle.find(params[:id])
		@vehicle.destroy
		redirect_to vehicles_path,notice: "Successfully deleted the #{@vehicle.name} Vehicle and Vehicle details"
		
	end

	def vehicle_params
		params[:vehicle].permit(:id,:name,:vehicle_type,:reg_no,:chassis_no,:engine_no,{:driver_ids => []}, :rc_image, :insurance_image, :emission_image, :rc_expiration_date, :insurance_expiration_date, :emission_expiration_date)
	end 

end

app/helpers/accessories_helper.rb
module AccessoriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/index.html.erb
<h3>Listing Vehicles </h3>

 <div class="table-responsive">          
  <table class="table" border="1">
  	<thead>
		<tr>
			<th>VehicleName</th>
			<th>RegistrationNumber</th>
			<th>Actions </th>
			
		</tr>
	</thead>
		<tbody>
			<tr>
				<% for vehicle in @vehicles %>
					<td><%= vehicle.name %></td>
					<td><%= vehicle.reg_no %></td>	
					<td><%= link_to "Show",vehicle_path(vehicle.id) %> |
						<%= link_to "Edit",edit_vehicle_path(vehicle.id) %> |
						<%= link_to "Delete",vehicle_path(vehicle.id), method: :delete,data:{confirm:"This vehicle is associated with different routes and drivers,are you sure"}%>
			</td>
		
			</tr>
		</tbody>
<% end %>
</table>
</div>
<br/>

<%= link_to "Add New Vehicle", new_vehicle_path %><br/><br/>

<h3>Listing Drivers</h3><br/>
<div class="table-responsive">          
  <table class="table" border="1">
 	<thead>
		<tr>
			<th>#</th>
			<th>Name</th>
			<th>Mobile No</th>
			<th>Emergency Contact</th>
			<th>Action</th>
        </tr>
	</thead>

    <tbody>
    	<% @drivers.each_with_index do |driver,index| %>
          <tr>
          	    <td><%= index + 1 %></td>
          	    <td><%= driver.name %></td>
          	    <td><%= driver.mobile_no %></td>
          	    <td><%= driver.emergency_contact %></td>
          	    <td><%= link_to "Show", driver_path(driver.id) %> |
          	    	<%= link_to "Edit", edit_driver_path(driver.id) %> |
          	    	<%= link_to "Delete", driver_path(driver.id), method: :delete, data: {confirm: "Are you sure?"} %></td>

          </tr>

          <% end %>

    </tbody>

	</table><br/>
</div>
<%= link_to "Add New Driver" , new_driver_path %><br/><br/>

<h3>Listing Clients</h3>

<br/>
<div class="table-responsive">          
  <table class="table" border="1">
 	<thead>
           <tr>
           	   <th> </th>
           	   <th>Name</th>
           	   <th>Email</th>
           	   <th>Phone</th>
           	   <th>Action</th>
           </tr>
      </thead>

      <tbody>
      	   <% @clients.each_with_index do |client,index| %>
                   <tr>
                        <td><%= index + 1 %></td>
                        <td><%= client.name %></td>
                        <td><%= client.email %></td>
                        <td><%= client.phone %></td>
                        <td><%= link_to "Show", client_path(client.id) %> |
          	    	        <%= link_to "Edit", edit_client_path(client.id) %> |
          	    	        <%= link_to "Delete", client_path(client.id), method: :delete, data: {confirm: "Are you sure?"} %></td>  
                   </tr>
      	   <% end %>
      </tbody>
</table><br/>
</div>

<%= link_to "Add New Client " , new_client_path %><br/><br/>


<h3>Listing Routes</h3>

<br/>
<div class="table-responsive">          
  <table class="table" border="1">
   <thead>
	  <tr> 
            <th>   </th>
            <th>Name</th>
            <th>Action</th>
	  </tr>
  </thead>

  <tbody>
          <% @routes.each_with_index do |route,index| %>
           <tr>
               <td><%= index + 1 %></td>
               <td><%= route.name %></td>
               <td><%= link_to "Show", route_path(route.id) %> |
          	    	<%= link_to "Edit", edit_route_path(route.id) %> |
          	    	<%= link_to "Delete", route_path(route.id), method: :delete, data: {confirm: "Are you sure?"} %></td>
           </tr> 
           <% end %>
  </tbody>

</table><br/>

</div>
<%#= link_to "Add New Location " ,new_location_path %>
<%= link_to "Add New Route " , new_route_path %><br/><br/>

<h3>Listing Locations</h3>

<br/>
<div class="table-responsive">          
  <table class="table" border="1">
   <thead>
    <tr> 
            <th>   </th>
            <th>Name</th>
            <th>Action</th>
    </tr>
  </thead>

  <tbody>
          <% @locations.each_with_index do |location,index| %>
           <tr>
               <td><%= index + 1 %></td>
               <td><%= location.name %></td>
                <td><%= link_to "Show", location_path(location.id) %> |
                  <%= link_to "Edit", edit_location_path(location.id) %> |
                  <%= link_to "Delete", location_path(location.id), method: :delete, data: {confirm: "Are you sure?"} %></td>
           </tr> 
           <% end %>
  </tbody>

</table><br/>

</div>
<%= link_to "Add New Location " ,new_location_path %><br/><br/>

app/views/vehicles/show.html.erb
<h3>Vehicle details</h3>
  <div class="table-responsive">          
  <table class="table" border="1">
	<thead>
		<tr>
			<th>Name:</th>
			<th>Type of the vehicle:</th>
			<th>Registration number:</th>
			<th>Driver name</th>
			<th>Actions </th>
		</tr>
	</thead>
		<tbody>
			<tr>
				<td><%= @vehicle.name %></td>
				<td><%= @vehicle.vehicle_type %></td>
				<td><%= @vehicle.reg_no %></td>
				<td><% for driver in @vehicle.drivers %>
        			<%= driver.name %><br/><% end %></td>
				<td><%= link_to "Edit",edit_vehicle_path(@vehicle.id) %> |
					<%= link_to "Delete",vehicle_path(@vehicle.id), method: :delete,data:{confirm: "Are you sure"}%> |
					<%= link_to "Back", vehicles_path %></td>
			</tr>
		</tbody>	
</table>
</div>

<div class="table-responsive">          
  <table class="table" border="1">
	<thead>
		<tr>
			<th>RC Expiration:</th>
			<th>Rc Image:</th>
			<th>Insurance Expiration:</th>
			<th>Insurance Image:</th>
			<th>Emission Expiration:</th>
			<th>Emission Image:</th>
		</tr>
	</thead>
		<tbody>
			<tr>
				<td><%= @vehicle.rc_expiration_date %></td>
				<td><%= image_tag @vehicle.rc_image.url %></td>
				<td><%= @vehicle.insurance_expiration_date %></td>
				<td><%= image_tag @vehicle.insurance_image.url %></td>
				<td><%= @vehicle.emission_expiration_date %></td>
				<td><%= image_tag @vehicle.emission_image.url %></td>	
			</tr>
		</tbody>	
</table>
</div>



<hr>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<style type="text/css">
    .bs-example{
    	margin: 20px;
    }
</style>
</head>
<body>
<div class="bs-example">
    <div class="panel-group" id="accordion">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Accessories Details</a>
                </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse in">
                <div class="panel-body">
                   <div class="table-responsive">          
					  <table class="table" border="1">
						<thead>
							<tr>
								<th>Name Of Accessory</th>
								<th>Cost</th>
								<th>Model</th>
								<th>Serial No</th>
								<th>Invoice image</th>
								<th>Actions </th>
								
							</tr>
						</thead>
							<tbody>
								<% for accessory in @vehicle.accessories %> 
									<tr>
										<td><%= accessory.name %></td>
										<td><%= accessory.cost %></td>
										<td><%= accessory.model %></td>
										<td><%= accessory.serial_no %></td>
										<td><%= image_tag accessory.invoice_image.url %></td>
										<td><%= link_to "Show",accessory_path(accessory.id) %>|
											<%= link_to "Edit",edit_accessory_path(accessory.id) %> |
											<%= link_to "Delete",accessory_path(accessory.id), method: :delete,data:{confirm: "Are you sure"}%></td>
									</tr>
									<% end %>
							</tbody>
					</table>
			</div></div>
        </div>
    </div>
 <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">Add Accessory </a>
                </h4>
            </div>
            <div id="collapseTwo" class="panel-collapse collapse">
                <div class="panel-body">
				
					<%= form_for Accessory.new , html: { multipart: true } do |t| %>
		
					<label>Name of Accessory</label><br/>
					<%= t.text_field :name %><br/>

					<label>Cost </label><br/>
					<%= t.text_field :cost %><br/>

					<label>Model</label></br>
					<%= t.text_field :model %><br/><br/>
					
					<label>Serial No</label></br>
					<%= t.text_field :serial_no %><br/><br/>
					
					<label>Invoice Image</label></br>
					<%= t.file_field :invoice_image %><br/><br/>

					<%= t.hidden_field :vehicle_id, value: @vehicle.id %><br/>

					<input type="submit" class="btn btn-info" value="Create Accesory">
	
					<% end -%>                    
                </div>
            </div>
    </div>

<div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseFive">Vehicle Payment Details of EMI</a>
                </h4>
            </div>
            <div id="collapseFive" class="panel-collapse collapse">
                <div class="panel-body">
                    <div class="table-responsive">          
					  <table class="table" border="1">
						<thead>
							<tr>
								<th>Payment Type</th>
								<th>Amount Paid</th>
								<th>Payment Date</th>
								<th>Mode of Payment</th>
								<th>Actions </th>
							</tr>
						</thead>
							<tbody>
								<% for vehicle_payment in @vehicle.vehicle_payments.where("amount_type = ?","EMI") %> 
								<tr>
									<td> <%= vehicle_payment.amount_type %></td>
									<td><%= vehicle_payment.amount_paid %></td>	
									<td><%= vehicle_payment.payment_date %></td>
									<td><%= vehicle_payment.mode_of_payment %></td>
									<td><%= link_to "Show",vehicle_payment_path(vehicle_payment.id) %> |
											<%= link_to "Edit",edit_vehicle_payment_path(vehicle_payment.id) %> |
											<%= link_to "Delete",vehicle_payment_path(vehicle_payment.id), method: :delete,data:{confirm: "Are you sure"}%></td>
								</tr>
								<% end %>	
							</tbody>
					</table>
</div></div></div></div>
<div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseSix">Vehicle Payment Details of Down-Payment</a>
                </h4>
            </div>
    <div id="collapseSix" class="panel-collapse collapse">
          <div class="panel-body">
                    <div class="table-responsive">          
					  <table class="table" border="1">
						<thead>
							<tr>
								<th>Payment Type</th>
								<th>Amount Paid</th>
								<th>Payment Date</th>
								<th>Mode of Payment</th>
								<th>Actions </th>
							</tr>
						</thead>
							<tbody>
									<% for vehicle_payment in @vehicle.vehicle_payments.where("amount_type = ?","Down-payment") %> 
									<tr>
									<td> <%= vehicle_payment.amount_type %></td>
									<td><%= vehicle_payment.amount_paid %></td>	
									<td><%= vehicle_payment.payment_date %></td>
									<td><%= vehicle_payment.mode_of_payment %></td>
									<td><%= link_to "Show",vehicle_payment_path(vehicle_payment.id) %> |
										<%= link_to "Edit",edit_vehicle_payment_path(vehicle_payment.id) %> |
										<%= link_to "Delete",vehicle_payment_path(vehicle_payment.id), method: :delete,data:{confirm: "Are you sure"}%></td>
									</tr>
									<% end %>	
							</tbody>
					</table>
	</div></div></div></div>
    <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseSeven">Vehicle Payment Details of Fuel</a>
                </h4>
            </div>
            <div id="collapseSeven" class="panel-collapse collapse">
                <div class="panel-body">
                    <div class="table-responsive">          
					  <table class="table" border="1">
						<thead>
							<tr>
								<th>Payment Type</th>
								<th>Amount Paid</th>
								<th>Payment Date</th>
								<th>Mode of Payment</th>
								<th>Actions </th>
							</tr>
						</thead>
							<tbody>
							<% for vehicle_payment in @vehicle.vehicle_payments.where("amount_type = ?","Fuel") %> 
							<tr>
								<td> <%= vehicle_payment.amount_type %></td>
								<td><%= vehicle_payment.amount_paid %></td>	
								<td><%= vehicle_payment.payment_date %></td>
								<td><%= vehicle_payment.mode_of_payment %></td>
								<td><%= link_to "Show",vehicle_payment_path(vehicle_payment.id) %> |
									<%= link_to "Edit",edit_vehicle_payment_path(vehicle_payment.id) %> |
									<%= link_to "Delete",vehicle_payment_path(vehicle_payment.id), method: :delete,data:{confirm: "Are you sure"}%></td>
							</tr>
							<% end %>	
						</tbody>
					</table>
					<h3>Total VehiclePayments of Fuel <%= @vehicle.vehicle_payments.where("amount_type = ?","Fuel").sum :amount_paid %></h3>

	</div></div></div></div>

	<div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseNine">Vehicle Payment Details of Service</a>
                </h4>
            </div>
            <div id="collapseNine" class="panel-collapse collapse">
                <div class="panel-body">
                    <div class="table-responsive">          
					  <table class="table" border="1">
						<thead>
							<tr>
								<th>Payment Type</th>
								<th>Amount Paid</th>
								<th>Payment Date</th>
								<th>Mode of Payment</th>
								<th>Actions </th>
							</tr>
						</thead>
							<tbody>
								<% for vehicle_payment in @vehicle.vehicle_payments.where("amount_type = ?","Service") %> 
								<tr>
								<td> <%= vehicle_payment.amount_type %></td>
								<td><%= vehicle_payment.amount_paid %></td>	
								<td><%= vehicle_payment.payment_date %></td>
								<td><%= vehicle_payment.mode_of_payment %></td>
								<td><%= link_to "Show",vehicle_payment_path(vehicle_payment.id) %> |
									<%= link_to "Edit",edit_vehicle_payment_path(vehicle_payment.id) %> |
									<%= link_to "Delete",vehicle_payment_path(vehicle_payment.id), method: :delete,data:{confirm: "Are you sure"}%></td>
								</tr>
								<% end %>	
							</tbody>
					</table>
</div></div></div></div>

	<div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseTen">Vehicle Payment Details </a>
                </h4>
            </div>
            <div id="collapseTen" class="panel-collapse collapse">
                <div class="panel-body">
                    <div class="table-responsive">          
					  <table class="table" border="1">
						<thead>
							<tr>
								<th>Payment Type</th>
								<th>Amount Paid</th>
								<th>Payment Date</th>
								<th>Mode of Payment</th>
								<th>Actions </th>
							</tr>
						</thead>
							<tbody>
								<% for vehicle_payment in @vehicle.vehicle_payments %> 
								<tr>
								<td> <%= vehicle_payment.amount_type %></td>
								<td><%= vehicle_payment.amount_paid %></td>	
								<td><%= vehicle_payment.payment_date %></td>
								<td><%= vehicle_payment.mode_of_payment %></td>
								<td><%= link_to "Show",vehicle_payment_path(vehicle_payment.id) %> |
									<%= link_to "Edit",edit_vehicle_payment_path(vehicle_payment.id) %> |
									<%= link_to "Delete",vehicle_payment_path(vehicle_payment.id), method: :delete,data:{confirm: "Are you sure"}%></td>
								</tr>
								<% end %>	
							</tbody>
					</table>
</div></div></div></div>

    <div class="panel panel-default">
           <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseEleven">Add Vehicle Payment Details</a>
                </h4>
            </div>
            <div id="collapseEleven" class="panel-collapse collapse">
                <div class="panel-body">
                    <%= form_for @vehicle_payment, html: { multipart: true } do |t| %>

					<% if @vehicle_payment.errors.any? %>
						<h3>These errors prohibited this <%= @vehicle_payment.class %> from being saved</h3>
						<ul>
						<% for msg in @vehicle_payment.errors.full_messages %>
							<li><%= msg %></li>
							<% end -%>
						</ul>
					<% end -%>
					
					<label>Payment Type </label><br/>
					<%= t.select :amount_type,["Down-payment","EMI","Fuel","Service"],prompt:"select_record"%><br/>

					<label>Amount Paid </label><br/>
					<%= t.text_field :amount_paid %><br/>

					<label>Payment Date</label></br>
					<%= t.date_select :payment_date,order: [:day,:month,:year],include_blank:true,start_year:Date.today.year %><br/>
					
					<label>Mode of Payment</label><br/>

					<%= t.select :mode_of_payment,["Cash","Card"],prompt:"select_record"%><br/>
					
					<%= t.hidden_field :vehicle_id,value: @vehicle.id %><br/>

					<label>Payment Image </label><br/>
					<%= t.file_field :image %><br/>

					<input type="submit" class="btn btn-info" value="Create Vehicle Payment">

				<% end -%>
                </div>
            </div>
        </div>
</div>
</div>
</body>
</html>      
<%#= pie_chart @vehicle.vehicle_payments.group(:amount_type).sum(:amount_paid) %>
<%#= column_chart @vehicle.vehicle_payments.group(:amount_type).sum(:amount_paid) %>

<p>Total Vehicle payments Of this vehicle is <strong>
<%= @vehicle.vehicle_payments.map(&:amount_paid).sum %></strong></p>

<% @vehicle_payment_months.each do |month,vehicle_payment | %>
<%= month.strftime("%B") %>
<%= vehicle_payment.map(&:amount_paid).sum %><br>
<% end -%>